create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  created_at timestamptz not null default now()
);

alter table public.posts enable row level security;

drop policy if exists "Public can read posts" on public.posts;
drop policy if exists "Public can create posts" on public.posts;
drop policy if exists "Public can delete posts" on public.posts;

create policy "Public can read posts"
on public.posts
for select
to anon
using (true);

create policy "Public can create posts"
on public.posts
for insert
to anon
with check (true);

create policy "Public can delete posts"
on public.posts
for delete
to anon
using (true);
